language: go

go:
  - 1.8
  - tip

install:
  - go get -v ./...
  - go get github.com/gin-gonic/gin
  - cd $GOPATH/src/github.com/gin-gonic/gin; git checkout ce784498b404909aad90c715099d38d0fabd3b1b
  - go get github.com/cention-sany/jsonapi
  - cd $GOPATH/src/github.com/google/jsonapi; git checkout 8fe2ebcbac8e4175c7aa0aae4f7436b7f12fb33a
